mp:
    processes:                  4

meteors:
    count:                      50000
    shape:
        dragCoefficient:        0.5                         # 0.47 for a spherical body
        shapeFactor:            1.21                        # 1.21 for a spherical body
    material:
        density:                
            distribution:       'gauss'
            parameters:         
                mean:           620
                sigma:          10
        heatTransfer:           0.5                         # Heat transfer coefficient, default 0.5
        ablationHeat:           6000000                     # Specific enthalpy of vaporization, in J/kg
    mass:
        distribution:           pareto                      # Particle mass distribution. Possible values 'pareto' or a number
        parameters:
            minimum:            0.000001
            shape:              2.1
    position:
        distribution:           'rectangle'                 # Name of the distribution, currently only 'rectangle'
        parameters:
            south:              43                          # Southern bound, degrees of latitude
            north:              53                          # Northern bound, degrees of latitude
            west:               12                          # Western bound, degrees of longitude
            east:               22                          # Eastern bound, degrees of longitude
            elevation:          130000                      # Initial elevation of meteors, in m
    velocity:
        distribution:           'shower'                    # Currently only 'shower'
        parameters:
            ra:                 151.7                       # Right ascension in degrees
            dec:                22                          # Declination in degrees
            speed:              71000                       # Entry speed in m/s
    time:
        distribution:           'uniform'
        parameters:
            begin:              2018-11-17T21:30:00         # Beginning of the interval, ISO8601
            end:                2018-11-18T05:00:00         # End of the interval, ISO8601
    integrator:                                             # Properties of the integrator
        name:                   'rk4'                       # Integrator to be used. Allowed values are 'rk4' and 'euler'.
        fps:                    50                          # Frames per second.
        spf:                    1                           # Steps per frame. Higher values mean more precise trajectories


observations:
    streaks:                    False
    minAltitude:                0
    observers:
        bratislava:
            latitude:           48.16
            longitude:          17.15
            altitude:           135

bias:
    magnitude:
        discriminator:          'sigmoid'                   # Magnitude detection efficiency profile, possible values 'sigmoid' or 'step'. Sigmoid is 1/(1 + exp((m - limit) / omega))
        parameters:
            limit:              4                           # Limiting magnitude m0
            width:              0.35                        # Width of the function
    angularSpeed:
        discriminator:          'all'                       # Angular speed detection efficiency profile, possible values 'flat' or 'linear'
        parameters:
            fillFactor:         1
            zero:               1
            slope:              -0.01
    altitude:
        discriminator:          all                         # Altitude detection efficiency profile, possible values 'step' or 'linear' or 'powersine'
        parameters:
            exponent:           0.25                        # Limit of altitude (sharp cutoff for 'step', zero efficiency for 'linear', 

plot:
    seenOnly:                   True
    sky:
        dark:                   True
        pixels:                 4000
        speed:                  False
        power:                  True
        sighted:                True
        angularSpeed:           True
        mass:                   True
        distance:               False
        elevation:              True

statistics:                                                 # Histograms to be plotted for simulation data
    histograms: 
        altitude:
            min:                0
            max:                90
            bin:                5
            name:               'altitude'
            xunit:              '°'
            xaxis:              'number'
        azimuth:
            min:                0
            max:                360
            bin:                15
            name:               'azimuth'
            xunit:              '°'
            xaxis:              'number'
        apparentMagnitude:
            min:                -10
            max:                10
            bin:                0.5
            name:               'apparent magnitude'
            xaxis:              'number'
        angularSpeed:
            min:                0
            max:                40
            bin:                1
            name:               'angular speed'
            xunit:              '°/s'
            xaxis:              'number'

multifit:                                                   # Exhaustive search of the parameter space
    magnitude:
        repeat:                 1
        function:               'sigmoid'
        parameters:
            limit:
                min:            -1
                max:            1
                step:           0.02
            omega:
                min:            0.02
                max:            0.8
                step:           0.02
    altitude:
        repeat:                 0
        function:               'powersine'
        parameters:
            exponent:
                min:            0.00
                max:            2.0
                step:           0.01
