mp:
    processes:                  4

meteors:
    count:                      1000
    shape:
        dragCoefficient:        0.5                         # 0.6 for a spherical body
        shapeFactor:            1.21                        # 1.21 for a spherical body
    material:
        density:                
            distribution:       'gauss'
            parameters:         
                mean:           620
                sigma:          10
        heatTransfer:           0.5                         # Heat transfer coefficient, default 0.5
        ablationHeat:           6000000                     # Specific enthalpy of vaporization, in J/kg
    mass:
        distribution:           'pareto'                    # Particle mass distribution. Possible values 'pareto', 'exponential' or a number
        parameters:
            minimum:            0.000005                    # Minimum particle mass, in kg
            shape:              2.00                        # Shape of the distribution, corresponds to s-index (N(m) \propto m^-s)
    position:
        distribution:           'rectangle'                 # Name of the distribution, currently only 'rectangle'
        parameters:
            south:              45                          # Southern bound, degrees of latitude
            north:              53                          # Northern bound, degrees of latitude
            west:               13                          # Western bound, degrees of longitude
            east:               27                          # Eastern bound, degrees of longitude
            elevation:          130000                      # Initial elevation of meteors, in m
    velocity:
        distribution:           'shower'                    # Currently only 'shower'
        parameters:
            ra:                 43                          # Right ascension in degrees
            dec:                56                          # Declination in degrees
            speed:              59000                       # Entry speed in m/s
    time:
        distribution:           'uniform'
        parameters:
            begin:              2016-08-11T19:00:00         # Beginning of the interval, ISO8601
            end:                2016-08-12T02:00:00         # End of the interval, ISO8601
    integrator:                                             
        name:                   'rk4'                       # Integrator to be used. Allowed values are 'rk4' and 'euler'.
        fps:                    20                          # Frames per second
        spf:                    1                           # Steps per frame. Higher values result in more precise trajectories but increase computation time

observations:
    streaks:                    False
    minAltitude:                0
    observers:
        teplicne:
            latitude:           48.68231
            longitude:          19.8575
            altitude:           692

bias:
    magnitude:
        discriminator:          'sigmoid'                   # Magnitude detection efficiency profile, possible values 'sigmoid' or 'step'. Sigmoid is 1/(1 + exp((m - limit) / omega))
        parameters:
            limit:              0.5                         # Limiting magnitude m0
            width:              0.35                        # Width of the function
    angularSpeed:
        discriminator:          'all'                       # Angular speed detection efficiency profile, possible values 'flat' or 'linear'
        parameters:
    altitude:
        discriminator:          'sinexp'                       # Altitude detection efficiency profile, possible values 'step' or 'linear' or 'sinexp'
        parameters:
            exponent:           0.1                         # Limit of altitude (sharp cutoff for 'step', zero efficiency for 'linear', 

plot:
    sky:
        dark:                   True
        pixels:                 4000
        quantities:
            speed:              False
            power:              True
            sighted:            True
            angularSpeed:       True
            mass:               True
            distance:           False
            elevation:          True

statistics:                                                 # Histograms to be plotted for simulation data
    histograms: 
        altitude:
            min:                0
            max:                90
            bin:                5
            name:               'altitude'
            xaxis:              'number'
        azimuth:
            min:                0
            max:                360
            bin:                15
            name:               'azimuth'
            xaxis:              'number'
        apparentMagnitude:
            min:                -12
            max:                12
            bin:                0.25
            name:               'apparent magnitude'
            xaxis:              'number'
        angularSpeed:
            min:                0
            max:                40
            bin:                1
            name:               'angular speed'
            xaxis:              'number'
        timestamp:
            min:                2016-08-11T19:00:00
            max:                2016-08-12T02:00:00
            bin:                600
            name:               'time'
            xaxis:              time

optimize:                                                   # Exhaustive search of the parameter space
    method:                     exhaustive
    repeat:                     1
    quantities:
        magnitude:
            function:           sigmoid
            parameters:
                limit:
                    min:        -6
                    max:        6
                    step:       0.5
                width:
                    min:        0.05
                    max:        1
                    step:       0.05
        altitude:
            function:           powersine
            parameters:
                exponent:
                    min:        -1.00
                    max:        2.00
                    step:       0.1
        angularSpeed:
            function:           power
            parameters:
                exponent:
                    min:        0.5
                    max:        1.5
                    step:       0.1
