generator:
    method:                     grid
    parameters:
        shape:
            dragCoefficient:    0.5
            shapeFactor:        1.21
        material:
            density:            625
            heatTransfer:       1.0
            ablationHeat:       6000000
        mass:                   0.001
        position:
            latitude:           90
            longitude:          90
            elevation:          150000
        velocity:
            ra:                 0
            dec:
                min:            10
                max:            90
                count:          30
                spacing:        log
            speed:              59000
        time:                   2019-03-21T21:58:00

integrator:                                             
    name:                       'rk4'                       # Integrator to be used. Allowed values are 'rk4' and 'euler'.
    fps:                        1000                        # Frames per second
    spf:                        1                           # Steps per frame. Higher values result in more precise trajectories but increase computation time
