generator:
    method:                     grid
    parameters:
        shape:
            dragCoefficient:    0.6
            shapeFactor:        1.21
        material:
            density:            625
            heatTransfer:       1.0
            ablationHeat:
                min:            1000
                max:            20000000
                count:          40
                spacing:        log
        mass:                   0.001
        position:
            latitude:           45
            longitude:          0
            elevation:          150000
        velocity:
            ra:                 0
            dec:                90
            speed:              59000
        time:                   2016-08-12T00:00:00

integrator:                                             
    name:                       'rk4'                       # Integrator to be used. Allowed values are 'rk4' and 'euler'.
    fps:                        1000                        # Frames per second
    spf:                        1                           # Steps per frame. Higher values result in more precise trajectories but increase computation time

