generator:
    method:                     grid
    parameters:
        shape:
            dragCoefficient:    0.5
            shapeFactor:        1.21
        material:
            density:            3000
            heatTransfer:       0.5
            ablationHeat:
                min:            1000
                max:            1000000000
                count:          121
                spacing:        log
        mass:                   0.001
        position:
            latitude:           90
            longitude:          0
            elevation:          180000
        velocity:
            ra:                 0
            dec:                45
            speed:              40000
        time:                   2016-06-21T00:00:00

integrator:                                             
    name:                       'rk4'                       # Integrator to be used. Allowed values are 'rk4' and 'euler'.
    fps:                        1000                         # Frames per second
    spf:                        1                           # Steps per frame. Higher values result in more precise trajectories but increase computation time
