_bias_functions:
    magnitude:   
        sigmoid: &sigmoid
            discriminator:      sigmoid                     # Magnitude detection efficiency profile, possible values 'sigmoid' or 'step'. Sigmoid is 1/(1 + exp((m - limit) / omega))
            parameters:                        
                limit:          6                           # Limiting magnitude m0
                width:          1                           # Width of the function
        all: &all
            discriminator:      'all'                       # Angular speed detection efficiency profile, possible values 'flat' or 'linear'
            parameters:
    altitude:
        sinexp: &powersine
            discriminator:      'sinexp'                    # Altitude detection efficiency profile, possible values 'step' or 'linear' or 'sinexp'
            parameters:
                exponent:       0.3                         # Limit of altitude (sharp cutoff for 'step', zero efficiency for 'linear', 

magnitude: *sigmoid
