mp:
    processes: 4
    report: 1

meteors:
    count:                      1

    shape:
        dragCoefficient:        0.5                         # 0.47 for a spherical body
        shapeFactor:            1.21                        # 1.21 for a spherical body

    material:
        density:                
            distribution:       constant                    # Density profile (see configuration/density.py). Possible values 'cometary', 'asteroid', 'iron', or a number (kg/m3)
            parameters:
                value:              635
        heatTransfer:           0.5                         # Heat transfer coefficient, default 0.5
        ablationHeat:           6000000                     # Specific enthalpy of vaporization, in J/kg

    mass:
        distribution:           'constant'                  # Particle mass distribution. Possible values 'pareto' or a number
        parameters:
            value:              0.07
    position:
        distribution:           pillow                      # Name of the distribution, currently only 'rectangle'
        parameters:
            south:              49.5036                     # Southern bound, degrees of latitude
            north:              49.5036                     # Northern bound, degrees of latitude
            west:               14.4436                     # Western bound, degrees of longitude
            east:               14.4436                     # Eastern bound, degrees of longitude
            bottom:             170180                      # Initial elevation of meteors, in m
            top:                170180                      # Initial elevation of meteors, in m
    velocity:
        distribution:           'shower'                    # Currently only 'shower'
        parameters:
            ra:                 46.756                      # Right ascension in degrees
            dec:                59.552                      # Declination in degrees
            speed:              59810                       # Entry speed in m/s
    time:
        distribution:           uniform
        parameters:
            begin:              2012-08-12T22:29:46         # Beginning of the interval, ISO8601
            end:                2012-08-12T22:29:46         # End of the interval, ISO8601

    integrator:                                                 # Properties of the integrator
        name: 'rk4'                                             # Integrator to be used. Allowed values are 'rk4' and 'euler'.
        fps: 1000                                                 # Frames per second.
        spf: 1                                                # Steps per frame. Higher values mean more precise trajectories
