generator:
    method:                     grid
    parameters:
        shape:
            dragCoefficient:    0.5
            shapeFactor:        1.21
        material:
            density:            2625
            heatTransfer:       0.5
            ablationHeat:       6000000
        mass:                   0.001
        position:
            latitude:           89
            longitude:          90
            elevation:          300000
        velocity:
            ra:                 0
            dec:                45
            speed:
                min:            50000
                max:            500000
                count:          19
                spacing:        log
        time:                   2016-06-21T00:00:00

integrator:                                             
    name:                       'rk4'                       # Integrator to be used. Allowed values are 'rk4' and 'euler'.
    fps:                        1000                        # Frames per second
    spf:                        1                           # Steps per frame. Higher values result in more precise trajectories but increase computation time
