generator:
    method:                     grid
    parameters:
        shape:
            dragCoefficient:    0.5
            shapeFactor:        1.21
        material:
            density:            2625
            heatTransfer:       0.5
            ablationHeat:       6000000
        mass:                   0.001
        position:
            latitude:           90
            longitude:          0
            elevation:          150000
        velocity:
            ra:                 
                min:            0
                max:            340
                count:          18
            dec:                30
            speed:          
                min:            22000
                max:            72000
                spacing:        log
                count:          11
        time:                   2016-08-12T00:00:00

integrator:                                             
    name:                       'rk4'                       # Integrator to be used. Allowed values are 'rk4' and 'euler'.
    fps:                        100                         # Frames per second
    spf:                        1                           # Steps per frame. Higher values result in more precise trajectories but increase computation time

