mp:                                                         # Multiprocessing configuration
    processes:                  1                           # Number of parallel processes to use (should be equal to number of cores)
    report:                     0.1                         # Report progress every N seconds

meteors:
    count:                      1

    shape:
        dragCoefficient:        
            distribution:       constant
            parameters:
                value:          0.6                         # 0.6 for a spherical body
        shapeFactor:            1.21                        # 1.21 for a spherical body

    material:
        density:                
            distribution:       'constant'
            parameters:
                value:          3500 
        heatTransfer:           0.15                        # Heat transfer coefficient, default 0.5
        ablationHeat:           3000000                     # Specific enthalpy of vaporization, in J/kg

    mass:
        distribution:           constant                    # Particle mass distribution. Possible values 'pareto', 'exponential' or a number
        parameters:
            value:              0.001

    position:
        distribution:           constant
        parameters:
            latitude:           49
            longitude:          20
            elevation:          150000

    velocity:
        distribution:           'shower'                    # Currently only 'shower'
        parameters:
            ra:                 23                          # Right ascension in degrees
            dec:                56                          # Declination in degrees
            speed:              20000                       # Entry speed in m/s

    time:
        distribution:           constant
        parameters:
            value:              2019-06-10T02:00:00

    integrator:                                             
        name:                   'rk4'                       # Integrator to be used. Allowed values are 'rk4' and 'euler'.
        fps:                    20                          # Frames per second
        spf:                    1                           # Steps per frame. Higher values result in more precise trajectories but increase computation time
