generator:
    method:                     grid
    parameters:
        shape:
            dragCoefficient:    0.5
            shapeFactor:        1.21
        material:
            density:            625
            heatTransfer:       0.5
            ablationHeat:       6000000
        mass:                   0.001
        position:
            latitude:           49
            longitude:          20
            elevation:          150000
        velocity:
            ra:                 43
            dec:                56
            speed:              59000
        time:                   
            min:                2016-08-11T00:00:00
            max:                2016-08-11T23:00:00
            count:              24

integrator:                                             
    name:                       'rk4'                       # Integrator to be used. Allowed values are 'rk4' and 'euler'.
    fps:                        1000                        # Frames per second
    spf:                        1                           # Steps per frame. Higher values result in more precise trajectories but increase computation time

