campaign:
    observers:
        ago:
            latitude:           48.3729
            longitude:          17.2738
            altitude:           538
            horizon:            15
            name:               'AGO'
