mp:
    processes:                  4
    report:                     1

observations:
    streaks:                    False
    observers:
        teplicne:
            name:               'Tepličné'
            latitude:           48.68231
            longitude:          19.8575
            altitude:           692
            horizon:            15
