quantities:                 &quantities
    altitude:               &altitude
        min:                0
        max:                90
        bin:                1
        name:               'altitude'
    azimuth:                &azimuth
        min:                0
        max:                360
        bin:                5
        name:               'azimuth'
    apparent_magnitude:     &apparent_magnitude
        min:                -15
        max:                10
        bin:                0.25
        name:               'apparent magnitude'
    absolute_magnitude:     &absolute_magnitude
        min:                -15
        max:                10
        bin:                0.25
        name:               'absolute magnitude'
    angular_speed:          &angular_speed
        min:                0
        max:                40
        bin:                1
        name:               'angular speed'
    logMassInitial:         &logMassInitial
        min:                -6.5
        max:                1
        bin:                0.1
        name:               'log initial mass'
    log_mass:                &logMass
        min:                -8
        max:                1
        bin:                0.1
        name:               'log mass'
    mjd:                    &mjd
        min:                57611.791666
        max:                57612.083333
        bin:                0.0069444444
        name:               'MJD'
    elevation:              &elevation
        min:                50000
        max:                130000
        bin:                1000
        name:               'elevation'
    entryAngle:             &entryAngle
        min:                20
        max:                80
        bin:                2
        name:               'entry angle'
    time:                   &time
        min:                0
        max:                5
        bin:                0.1
        name:               'flight time'
    speed:                  &speed
        min:                0
        max:                80000
        bin:                1000
        name:               'speed'
    density:
        min:                0
        max:                10000
        bin:                500
        name:               'density'
    logDensity:
        min:                0
        max:                5
        bin:                0.1
        name:               'log density'

