biasFunctions:
    magnitude:   
        sigmoid: &sigmoid
            discriminator:      sigmoid                     # Magnitude detection efficiency profile, possible values 'sigmoid' or 'step'. Sigmoid is 1/(1 + exp((m - limit) / omega))
            parameters:                        
                limit:          0.4                         # Limiting magnitude m0
                width:          0.35                        # Width of the function
        all: &all
            discriminator:      'all'                       # Angular speed detection efficiency profile, possible values 'flat' or 'linear'
            parameters:
    altitude:
        sinexp: &sinexp
            discriminator:      'sinexp'                    # Altitude detection efficiency profile, possible values 'step' or 'linear' or 'sinexp'
            parameters:
                exponent:       0.4                         # Limit of altitude (sharp cutoff for 'step', zero efficiency for 'linear', 

bias:
    magnitude: *sigmoid
    angularSpeed: *all
    altitude: *all

plot:
    sky:
        dark:                   True
        pixels:                 4000

statistics:                                                 # Histograms to be plotted for simulation data
    quantities: &quantities
        altitude: &altitude
            min:                0
            max:                90
            bin:                1
            name:               'altitude'
            xaxis:              'number'
        azimuth: &azimuth
            min:                0
            max:                360
            bin:                5
            name:               'azimuth'
            xaxis:              'number'
        appMag: &appMag
            min:                -15
            max:                10
            bin:                0.25
            name:               'apparent magnitude'
            xaxis:              'number'
        absMag: &absMag
            min:                -15
            max:                10
            bin:                0.25
            name:               'absolute magnitude'
            xaxis:              'number'
        angSpeed: &angSpeed
            min:                0
            max:                40
            bin:                1
            name:               'angular speed'
            xaxis:              'number'
        logInitMass: &logInitMass
            min:                -6.5
            max:                1
            bin:                0.1
            name:               'log initial mass'
            xaxis:              'number'
        mjd: &mjd
            min:                57611.791666
            max:                57612.083333
            bin:                0.0069444444
            name:               'MJD'
            xaxis:              'number'
        elevation: &elevation
            min:                60000
            max:                150000
            bin:                1000
            name:               'elevation'
            xaxis:              'number'
#        timestamp:
#            min:                2016-08-11T19:00:00
#            max:                2016-08-12T02:00:00
#            bin:                600
#            name:               'time'
#            xaxis:              time

    histograms:
        quantities:             *quantities
    kdes:
        quantities:             *quantities
    scatters:
#        -   x:                  appMag
#            y:                  altitude
#            colour:             absMag
        -   {x:     appMag, y:      absMag, colour: absMag}
#        -   x:                  logInitMass
#            y:                  appMag
#            colour:             absMag
        -   x:                  logInitMass
            y:                  altitude
            colour:             absMag
        -   x:                  mjd
            y:                  altitude
            colour:             absMag
        -   x:                  mjd
            y:                  appMag
            colour:             absMag
        -   x:                  logInitMass
            y:                  elevation
            colour:             absMag
        -   x:                  mjd
            y:                  elevation
            colour:             absMag
        -   x:                  mjd
            y:                  angSpeed
            colour:             appMag
        -   {x:   altitude,     y:    angSpeed, colour: appMag}
        -   {x:     appMag,     y:   elevation, colour: logInitMass}
        -   {x:     appMag,     y: logInitMass, colour: logInitMass}


optimize:                                                   # Exhaustive search of the parameter space
    method:                     exhaustive
    repeat:                     1
    quantities:
        magnitude:
            function:           sigmoid
            parameters:
                limit:
                    min:        -6
                    max:        6
                    step:       0.5
                width:
                    min:        0.05
                    max:        1
                    step:       0.05
        altitude:
            function:           powersine
            parameters:
                exponent:
                    min:        -1.00
                    max:        2.00
                    step:       0.1
        angularSpeed:
            function:           power
            parameters:
                exponent:
                    min:        0.5
                    max:        1.5
                    step:       0.1
