quantities:                 &quantities
    ablation_heat:          &ablation_heat
        id:                 ablationHeat
        bin:                1
        unit:               'J/kg'
        name:               'heat of ablation'
        scale:              log
    altitude:               &altitude
        id:                 altitude
        bin:                1
        unit:               '°'
        name:               'altitude'
    azimuth:                &azimuth
        id:                 azimuth
        bin:                5
        name:               'azimuth'
        unit:               '°'
    apparent_magnitude:     &apparent_magnitude
        id:                 appMag
        bin:                0.25
        name:               'apparent magnitude'
    absolute_magnitude:     &absolute_magnitude
        id:                 absolute_magnitude
        bin:                0.25
        name:               'absolute magnitude'
    angular_speed:          &angular_speed
        id:                 ang_speed
        bin:                1
        name:               'angular speed'
        unit:               '°/s'
    log_mass_initial:       &lmi
        id:                 mass_initial
        bin:                0.1
        name:               'log initial mass'
        unit:               'kg'
        scale:              log
    mass:                   &mass
        id:                 mass
        bin:                0.1
        min:                0
        max:                0.0011
        name:               'mass'
        unit:               'kg'
    log_mass:               &log_mass
        id:                 mass
        bin:                0.1
        name:               'mass'
        unit:               'kg'
        scale:              log
    mjd:                    &mjd
        id:                 mjd
        bin:                0.0069444444
        name:               'MJD'
        unit:               'd'
    elevation:              &elevation
        id:                 elevation
        bin:                1000
        name:               'elevation'
        unit:               'm'
    entry_angle:            &entry_angle
        id:                 entry_angle
        bin:                2
        name:               'entry angle'
        unit:               '°'
    time:                   &time
        id:                 time
        bin:                0.1
        name:               'flight time'
        unit:               's'
    speed:                  &speed
        id:                 speed
        bin:                1000
        name:               'speed'
        unit:               'm/s'
    density:                &density
        id:                 density
        bin:                500
        name:               'density'
        unit:               'kg/m³'
    log_density:            &log_density
        id:                 density
        bin:                0.1
        name:               'density'
        unit:               'kg/m³'
        scale:              'log'
    mass_fraction:           &mf
        id:                 mass_fraction
        name:               'mass fraction'
    fpkg:                   &fpkg
        id:                 fpkg
        name:               'flux per mass'
        scale:              log
        unit:               'W/kg'
    fpkgi:                  &fpkgi
        id:                 fpkgi
        name:               'flux per initial mass'
        unit:               'W/kg'

#        timestamp:
#            min:                2016-08-11T19:00:00
#            max:                2016-08-12T02:00:00
#            bin:                600
#            name:               'time'
#            xaxis:              time

scatters:
    -   {x:             *time, y:        *absolute_magnitude, colour: *lmi, cmap: viridis}
    -   {x:             *time, y:         *speed, colour: *lmi, cmap: viridis}
    -   {x:              *lmi, y:         *speed, colour: *lmi, cmap: viridis}
    -   {x: *absolute_magnitude, y:     *elevation, colour: *lmi, cmap: viridis}
    -   {x:         *log_mass, y:        *absolute_magnitude, colour: *lmi, cmap: viridis}
    -   {x:              *lmi, y:        *absolute_magnitude, colour: *lmi, cmap: viridis}
    -   {x:              *lmi, y:            *mf, colour: *lmi, cmap: viridis}
    -   {x:             *time, y:          *fpkg, colour: *lmi, cmap: viridis}
    -   {x:             *time, y:         *fpkgi, colour: *lmi, cmap: viridis}
    -   {x:               *mf, y:          *fpkg, colour: *lmi, cmap: viridis}
    -   {x:               *mf, y:         *fpkgi, colour: *lmi, cmap: viridis}
    -   {x:               *mf, y:     *elevation, colour: *lmi, cmap: viridis}

histograms:
    -   id:     'apparent_magnitude'
        name:   'apparent magnitude'
        min:    -10
        max:    10
        bin:    0.5
